/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentenmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author emirhan
 */
public class Lehrer extends javax.swing.JFrame {
    
     Connection con = null;
     PreparedStatement pst=null;
     ResultSet rs=null;

    /**
     * Creates new form Lehrer
     */
    public Lehrer() {
        initComponents();
        show_user();
    }
 public ArrayList<user> userList(){
        ArrayList<user> usersList= new ArrayList<>();
        
     try { 
           Class.forName("org.hsqldb.jdbcDriver"); 
           String url = "jdbc:hsqldb:file:C:\\Users\\domin\\Desktop\\sql\\;shutdown=true";  
           con = DriverManager.getConnection(url,"G1", "1234");
           String query ="SELECT * FROM Lehrer";
           Statement st= con.createStatement();
           rs =st.executeQuery(query);
           user User;
            while(rs.next()){
                User =new user(rs.getString("Vorname"),rs.getString("Nachname"),rs.getString("Benutzername"),rs.getString("Passwort"),rs.getString("Telefonnummer"),rs.getString("Email"));
                usersList.add(User);
                
            
            }
           }
     
            catch (Exception e) { 
            JOptionPane.showMessageDialog(null,e);
       }
            return usersList;
    }
    public void show_user(){
    ArrayList<user> list = userList();
    DefaultTableModel model = (DefaultTableModel) Lehrer.getModel();
        Object[] row = new Object[6];
        for(int i=0;i<list.size();i++){
        row[0]=list.get(i).getVorname();
        row[1]=list.get(i).getNachname();
        row[2]=list.get(i).getBenutzername();
        row[3]=list.get(i).getPasswort();
        row[4]=list.get(i).getTel();
        row[5]=list.get(i).getEmail();
        model.addRow(row);
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        LehrerNeu = new javax.swing.JPanel();
        Vorname = new javax.swing.JLabel();
        Nachname = new javax.swing.JLabel();
        Tel = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        TfVorname = new javax.swing.JTextField();
        TfNachname = new javax.swing.JTextField();
        TfTel = new javax.swing.JTextField();
        TfEmail = new javax.swing.JTextField();
        Benutzername = new javax.swing.JLabel();
        Passwort = new javax.swing.JLabel();
        TfBenutzername = new javax.swing.JTextField();
        TfPasswort = new javax.swing.JTextField();
        jBLehrerSpeichern = new javax.swing.JButton();
        LehrerBearbeiten = new javax.swing.JPanel();
        VornameLb = new javax.swing.JLabel();
        NachnameLb = new javax.swing.JLabel();
        TfVornameLb = new javax.swing.JTextField();
        TfNachnameLb = new javax.swing.JTextField();
        BenutzernameLb = new javax.swing.JLabel();
        TfBenutzernameLb = new javax.swing.JTextField();
        jBLehrerEingebenLb = new javax.swing.JButton();
        jLayeredPaneB = new javax.swing.JLayeredPane();
        TfEmailBp = new javax.swing.JTextField();
        TfBenutzernameBp = new javax.swing.JTextField();
        VornameBp = new javax.swing.JLabel();
        BenutzernameBp = new javax.swing.JLabel();
        TfPasswortBp = new javax.swing.JTextField();
        NachnameBp = new javax.swing.JLabel();
        TelBp = new javax.swing.JLabel();
        PasswortBp = new javax.swing.JLabel();
        EmaiBp = new javax.swing.JLabel();
        TfVornameBp = new javax.swing.JTextField();
        TfNachnameBp = new javax.swing.JTextField();
        TfTelBp = new javax.swing.JTextField();
        jBLehrerSpeichernBp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lehrer = new javax.swing.JTable();
        LehrerSuchen = new javax.swing.JPanel();
        VornameLs = new javax.swing.JLabel();
        NachnameLs = new javax.swing.JLabel();
        TfVornameLs = new javax.swing.JTextField();
        TfNachnameLs = new javax.swing.JTextField();
        BenutzernameLs = new javax.swing.JLabel();
        TfBenutzernameLs = new javax.swing.JTextField();
        jBLehrerEingebenLs = new javax.swing.JButton();
        jLayeredPaneS = new javax.swing.JLayeredPane();
        TfEmailSp = new javax.swing.JTextField();
        TfBenutzernameSp = new javax.swing.JTextField();
        VornameSp = new javax.swing.JLabel();
        BenutzernameSp = new javax.swing.JLabel();
        TfPasswortSp = new javax.swing.JTextField();
        NachnameSp = new javax.swing.JLabel();
        TelSp = new javax.swing.JLabel();
        PasswortSp = new javax.swing.JLabel();
        EmailSp = new javax.swing.JLabel();
        TfVornameSp = new javax.swing.JTextField();
        TfNachnameSp = new javax.swing.JTextField();
        TfTelSp = new javax.swing.JTextField();
        jBLehrerOkaySp = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lehrer1 = new javax.swing.JTable();
        LehrerLöschen = new javax.swing.JPanel();
        VornameLl = new javax.swing.JLabel();
        NachnameLl = new javax.swing.JLabel();
        TfVornameLl = new javax.swing.JTextField();
        TfNachnameLl = new javax.swing.JTextField();
        BenutzernameLl = new javax.swing.JLabel();
        TfBenutzernameLl = new javax.swing.JTextField();
        jBLehrerLöschenLl = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lehrer2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Vorname.setText("Vorname");

        Nachname.setText("Nachname");

        Tel.setText("Telefonnummer");

        Email.setText("Email");

        TfVorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfVornameActionPerformed(evt);
            }
        });

        TfNachname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNachnameActionPerformed(evt);
            }
        });

        TfTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfTelActionPerformed(evt);
            }
        });

        Benutzername.setText("Benutzername");

        Passwort.setText("Passwort");

        jBLehrerSpeichern.setText("Speichern");
        jBLehrerSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLehrerSpeichernActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LehrerNeuLayout = new javax.swing.GroupLayout(LehrerNeu);
        LehrerNeu.setLayout(LehrerNeuLayout);
        LehrerNeuLayout.setHorizontalGroup(
            LehrerNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LehrerNeuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(LehrerNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LehrerNeuLayout.createSequentialGroup()
                        .addComponent(Email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LehrerNeuLayout.createSequentialGroup()
                        .addComponent(Tel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TfTel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LehrerNeuLayout.createSequentialGroup()
                        .addComponent(Passwort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TfPasswort, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LehrerNeuLayout.createSequentialGroup()
                        .addComponent(Benutzername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(TfBenutzername, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LehrerNeuLayout.createSequentialGroup()
                        .addGroup(LehrerNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Vorname)
                            .addComponent(Nachname))
                        .addGap(97, 97, 97)
                        .addGroup(LehrerNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TfNachname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(TfVorname, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(578, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LehrerNeuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBLehrerSpeichern)
                .addGap(64, 64, 64))
        );
        LehrerNeuLayout.setVerticalGroup(
            LehrerNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LehrerNeuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LehrerNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vorname, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(LehrerNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nachname))
                .addGap(18, 18, 18)
                .addGroup(LehrerNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Benutzername)
                    .addComponent(TfBenutzername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LehrerNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfPasswort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Passwort))
                .addGap(18, 18, 18)
                .addGroup(LehrerNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tel)
                    .addComponent(TfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(LehrerNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(jBLehrerSpeichern)
                .addGap(102, 102, 102))
        );

        jTabbedPane1.addTab("Lehrer neu", LehrerNeu);

        VornameLb.setText("Vorname");

        NachnameLb.setText("Nachname");

        TfVornameLb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfVornameLbActionPerformed(evt);
            }
        });
        TfVornameLb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfVornameLbKeyReleased(evt);
            }
        });

        TfNachnameLb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfNachnameLbKeyReleased(evt);
            }
        });

        BenutzernameLb.setText("Benutzername");

        TfBenutzernameLb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfBenutzernameLbKeyReleased(evt);
            }
        });

        jBLehrerEingebenLb.setText("Eingeben");
        jBLehrerEingebenLb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLehrerEingebenLbActionPerformed(evt);
            }
        });

        TfEmailBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEmailBpActionPerformed(evt);
            }
        });

        VornameBp.setText("Vorname");

        BenutzernameBp.setText("Benutzername");

        NachnameBp.setText("Nachname");

        TelBp.setText("Telefonnummer");

        PasswortBp.setText("Passwort");

        EmaiBp.setText("Email");

        TfVornameBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfVornameBpActionPerformed(evt);
            }
        });

        jLayeredPaneB.setLayer(TfEmailBp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneB.setLayer(TfBenutzernameBp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneB.setLayer(VornameBp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneB.setLayer(BenutzernameBp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneB.setLayer(TfPasswortBp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneB.setLayer(NachnameBp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneB.setLayer(TelBp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneB.setLayer(PasswortBp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneB.setLayer(EmaiBp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneB.setLayer(TfVornameBp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneB.setLayer(TfNachnameBp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneB.setLayer(TfTelBp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneBLayout = new javax.swing.GroupLayout(jLayeredPaneB);
        jLayeredPaneB.setLayout(jLayeredPaneBLayout);
        jLayeredPaneBLayout.setHorizontalGroup(
            jLayeredPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VornameBp)
                    .addComponent(NachnameBp)
                    .addComponent(TelBp, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmaiBp)
                    .addComponent(BenutzernameBp)
                    .addComponent(PasswortBp))
                .addGap(60, 60, 60)
                .addGroup(jLayeredPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfEmailBp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfTelBp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfVornameBp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfNachnameBp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfBenutzernameBp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPasswortBp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jLayeredPaneBLayout.setVerticalGroup(
            jLayeredPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VornameBp)
                    .addComponent(TfVornameBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NachnameBp)
                    .addComponent(TfNachnameBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BenutzernameBp)
                    .addComponent(TfBenutzernameBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswortBp)
                    .addComponent(TfPasswortBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelBp)
                    .addComponent(TfTelBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmaiBp)
                    .addComponent(TfEmailBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jBLehrerSpeichernBp.setText("Speichern");
        jBLehrerSpeichernBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLehrerSpeichernBpActionPerformed(evt);
            }
        });

        Lehrer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vorname", "Nachname", "Benutzername", "Passwort", "Telefonnummer", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Lehrer.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LehrerAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Lehrer);

        javax.swing.GroupLayout LehrerBearbeitenLayout = new javax.swing.GroupLayout(LehrerBearbeiten);
        LehrerBearbeiten.setLayout(LehrerBearbeitenLayout);
        LehrerBearbeitenLayout.setHorizontalGroup(
            LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                .addGroup(LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPaneB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBLehrerEingebenLb)
                                .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                                    .addGroup(LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                                            .addComponent(BenutzernameLb)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                            .addComponent(TfBenutzernameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                                            .addGroup(LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(VornameLb)
                                                .addComponent(NachnameLb))
                                            .addGap(97, 97, 97)
                                            .addGroup(LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(TfNachnameLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                                .addComponent(TfVornameLb, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addGap(32, 32, 32)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                                .addGap(684, 684, 684)
                                .addComponent(jBLehrerSpeichernBp)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        LehrerBearbeitenLayout.setVerticalGroup(
            LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                .addGroup(LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfVornameLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VornameLb, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfNachnameLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NachnameLb, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(BenutzernameLb))
                            .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TfBenutzernameLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jBLehrerEingebenLb)
                .addGroup(LehrerBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LehrerBearbeitenLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLayeredPaneB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LehrerBearbeitenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBLehrerSpeichernBp)
                        .addGap(98, 98, 98))))
        );

        jTabbedPane1.addTab("Lehrer bearbeiten", LehrerBearbeiten);

        LehrerSuchen.setToolTipText("");

        VornameLs.setText("Vorname");

        NachnameLs.setText("Nachname");

        BenutzernameLs.setText("Benutzername");

        jBLehrerEingebenLs.setText("Eingeben");
        jBLehrerEingebenLs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLehrerEingebenLsActionPerformed(evt);
            }
        });

        VornameSp.setText("Vorname");

        BenutzernameSp.setText("Benutzername");

        NachnameSp.setText("Nachname");

        TelSp.setText("Telefonnummer");

        PasswortSp.setText("Passwort");

        EmailSp.setText("Email");

        jLayeredPaneS.setLayer(TfEmailSp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneS.setLayer(TfBenutzernameSp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneS.setLayer(VornameSp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneS.setLayer(BenutzernameSp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneS.setLayer(TfPasswortSp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneS.setLayer(NachnameSp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneS.setLayer(TelSp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneS.setLayer(PasswortSp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneS.setLayer(EmailSp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneS.setLayer(TfVornameSp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneS.setLayer(TfNachnameSp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneS.setLayer(TfTelSp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneSLayout = new javax.swing.GroupLayout(jLayeredPaneS);
        jLayeredPaneS.setLayout(jLayeredPaneSLayout);
        jLayeredPaneSLayout.setHorizontalGroup(
            jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TfNachnameSp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPaneSLayout.createSequentialGroup()
                        .addGroup(jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VornameSp)
                            .addComponent(EmailSp)
                            .addComponent(TelSp, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswortSp)
                            .addComponent(BenutzernameSp)
                            .addComponent(NachnameSp))
                        .addGroup(jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPaneSLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(TfVornameSp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneSLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfBenutzernameSp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfPasswortSp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfTelSp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfEmailSp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jLayeredPaneSLayout.setVerticalGroup(
            jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VornameSp)
                    .addComponent(TfVornameSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NachnameSp)
                    .addComponent(TfNachnameSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BenutzernameSp)
                    .addComponent(TfBenutzernameSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswortSp)
                    .addComponent(TfPasswortSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelSp)
                    .addComponent(TfTelSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jLayeredPaneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailSp)
                    .addComponent(TfEmailSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jBLehrerOkaySp.setText("Okay");
        jBLehrerOkaySp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLehrerOkaySpActionPerformed(evt);
            }
        });

        jButton2.setText("Suchen");

        Lehrer1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vorname", "Nachname", "Benutzername", "Passwort", "Telefonnummer", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Lehrer1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Lehrer1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(Lehrer1);

        javax.swing.GroupLayout LehrerSuchenLayout = new javax.swing.GroupLayout(LehrerSuchen);
        LehrerSuchen.setLayout(LehrerSuchenLayout);
        LehrerSuchenLayout.setHorizontalGroup(
            LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LehrerSuchenLayout.createSequentialGroup()
                .addGroup(LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LehrerSuchenLayout.createSequentialGroup()
                        .addComponent(jLayeredPaneS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LehrerSuchenLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jBLehrerOkaySp, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LehrerSuchenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBLehrerEingebenLs))))
                    .addGroup(LehrerSuchenLayout.createSequentialGroup()
                        .addGroup(LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LehrerSuchenLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BenutzernameLs)
                                    .addComponent(VornameLs)
                                    .addComponent(NachnameLs))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfNachnameLs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfVornameLs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfBenutzernameLs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(LehrerSuchenLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );
        LehrerSuchenLayout.setVerticalGroup(
            LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LehrerSuchenLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LehrerSuchenLayout.createSequentialGroup()
                        .addGroup(LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VornameLs)
                            .addComponent(TfVornameLs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NachnameLs)
                            .addComponent(TfNachnameLs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BenutzernameLs)
                            .addComponent(TfBenutzernameLs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(LehrerSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LehrerSuchenLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLayeredPaneS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(104, Short.MAX_VALUE))
                    .addGroup(LehrerSuchenLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jBLehrerEingebenLs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBLehrerOkaySp)
                        .addGap(96, 96, 96))))
        );

        jTabbedPane1.addTab("Lehrer suchen", LehrerSuchen);

        VornameLl.setText("Vorname");

        NachnameLl.setText("Nachname");

        BenutzernameLl.setText("Benutzername");

        jBLehrerLöschenLl.setText("Löschen");
        jBLehrerLöschenLl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLehrerLöschenLlActionPerformed(evt);
            }
        });

        jButton3.setText("Suchen");

        Lehrer2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vorname", "Nachname", "Benutzername", "Passwort", "Telefonnummer", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Lehrer2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Lehrer2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(Lehrer2);

        javax.swing.GroupLayout LehrerLöschenLayout = new javax.swing.GroupLayout(LehrerLöschen);
        LehrerLöschen.setLayout(LehrerLöschenLayout);
        LehrerLöschenLayout.setHorizontalGroup(
            LehrerLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LehrerLöschenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBLehrerLöschenLl)
                .addGap(65, 65, 65))
            .addGroup(LehrerLöschenLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(LehrerLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LehrerLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(LehrerLöschenLayout.createSequentialGroup()
                            .addGroup(LehrerLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(VornameLl)
                                .addComponent(NachnameLl))
                            .addGap(97, 97, 97)
                            .addGroup(LehrerLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TfNachnameLl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(TfVornameLl, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LehrerLöschenLayout.createSequentialGroup()
                            .addComponent(BenutzernameLl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                            .addGroup(LehrerLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton3)
                                .addComponent(TfBenutzernameLl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(101, 101, 101))))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        LehrerLöschenLayout.setVerticalGroup(
            LehrerLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LehrerLöschenLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(LehrerLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VornameLl)
                    .addComponent(TfVornameLl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LehrerLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfNachnameLl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NachnameLl))
                .addGap(13, 13, 13)
                .addGroup(LehrerLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BenutzernameLl)
                    .addComponent(TfBenutzernameLl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(91, 91, 91)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jBLehrerLöschenLl)
                .addGap(99, 99, 99))
        );

        jTabbedPane1.addTab("Lehrer löschen", LehrerLöschen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLehrerLöschenLlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLehrerLöschenLlActionPerformed
        // TODO add your handling code here:
        TfVorname.setText("");
        TfNachname.setText("");
        TfBenutzername.setText("");
        TfPasswort.setText("");
        TfTel.setText("");
        TfEmail.setText("");
        TfVornameLb.setText("");
        TfNachnameLb.setText("");
        TfBenutzernameLb.setText("");
        TfPasswortBp.setText("");
        TfTelBp.setText("");
        TfEmailBp.setText("");
        TfVornameBp.setText("");
        TfNachnameBp.setText("");
        TfBenutzernameBp.setText("");
        TfVornameLs.setText("");
        TfNachnameLs.setText("");
        TfBenutzernameLs.setText("");
        TfVornameLl.setText("");
        TfNachnameLl.setText("");
        TfBenutzernameLl.setText("");
        
    }//GEN-LAST:event_jBLehrerLöschenLlActionPerformed

    private void jBLehrerEingebenLsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLehrerEingebenLsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLehrerEingebenLsActionPerformed

    private void jBLehrerSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLehrerSpeichernActionPerformed
               try { 
            System.out.println("Connecting database..."); 
            Class.forName("org.hsqldb.jdbcDriver"); 
            String url = "jdbc:hsqldb:file:C:\\Users\\domin\\Desktop\\sql\\;shutdown=true";           
            System.out.println("Database connected!"); 
            String query ="insert into Lehrer"   
               +"(Vorname,Nachname,Benutzername,Passwort,Telefonnummer,Email)"
               +"values(?,?,?,?,?,?)";
                   Connection con = DriverManager.getConnection(url,"G1", "1234"); 
                   PreparedStatement pst = con.prepareStatement(query);
               pst.setString(1,TfVorname.getText()); 
               pst.setString(2,TfNachname.getText());
               pst.setString(3,TfBenutzername.getText());
               pst.setString(4,TfPasswort.getText());
               pst.setString(5,TfTel.getText());
               pst.setString(6,TfEmail.getText());
                  pst.executeUpdate();
                  DefaultTableModel model = (DefaultTableModel) Lehrer.getModel();
                  model.setRowCount(0);
                  show_user();
            JOptionPane.showMessageDialog(null,"Gespeichert!");}      
        catch (ClassNotFoundException | SQLException e) { 
            JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_jBLehrerSpeichernActionPerformed

    private void jBLehrerEingebenLbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLehrerEingebenLbActionPerformed
     int row=Lehrer.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) Lehrer.getModel();
       
                      
                      TfVorname.setText(model.getValueAt(row, 0).toString());
                      
                      TfNachname.setText(model.getValueAt(row, 1).toString());   
                      
                      TfBenutzername.setText(model.getValueAt(row, 2).toString());
                      
                      TfPasswort.setText(model.getValueAt(row, 3).toString());
                      
                      TfTel.setText(model.getValueAt(row, 4).toString());
                      
                      TfEmail.setText(model.getValueAt(row, 5).toString());  

        // TODO add your handling code here:
    }//GEN-LAST:event_jBLehrerEingebenLbActionPerformed

    private void jBLehrerSpeichernBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLehrerSpeichernBpActionPerformed
 try { 
            System.out.println("Connecting database..."); 
            Class.forName("org.hsqldb.jdbcDriver"); 
            String url = "jdbc:hsqldb:file:C:\\Users\\domin\\Desktop\\sql\\;shutdown=true";           
            System.out.println("Database connected!"); 
            String query ="insert into Lehrer"   
               +"(Vorname,Nachname,Benutzername,Passwort,Telefonnummer,Email)"
               +"values(?,?,?,?,?,?)";
                   con = DriverManager.getConnection(url,"G1", "1234"); 
                   pst = con.prepareStatement(query);
               pst.setString(1,TfVornameBp.getText()); 
               pst.setString(2,TfNachnameBp.getText());
               pst.setString(3,TfBenutzernameBp.getText());
               pst.setString(4,TfPasswortBp.getText());
               pst.setString(5,TfTelBp.getText());
               pst.setString(6,TfEmailBp.getText());
                  pst.executeUpdate();
                  DefaultTableModel model = (DefaultTableModel) Lehrer.getModel();
                  model.setRowCount(0);
                  show_user();
            JOptionPane.showMessageDialog(null,"Gespeichert!");}      
        catch (ClassNotFoundException | SQLException e) { 
            JOptionPane.showMessageDialog(null,e);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jBLehrerSpeichernBpActionPerformed

    private void jBLehrerOkaySpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLehrerOkaySpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLehrerOkaySpActionPerformed

    private void TfEmailBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEmailBpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEmailBpActionPerformed

    private void TfVornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfVornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfVornameActionPerformed

    private void TfNachnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNachnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNachnameActionPerformed

    private void TfTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfTelActionPerformed

    private void LehrerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LehrerAncestorAdded
 
                    // TODO add your handling code here:
    }//GEN-LAST:event_LehrerAncestorAdded

    private void Lehrer1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Lehrer1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Lehrer1AncestorAdded

    private void Lehrer2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Lehrer2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Lehrer2AncestorAdded

    private void TfVornameLbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfVornameLbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfVornameLbActionPerformed

    private void TfVornameLbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfVornameLbKeyReleased
    
        try {             
            Class.forName("org.hsqldb.jdbcDriver"); 
            String url = "jdbc:hsqldb:file:C:\\Users\\domin\\Desktop\\sql\\;shutdown=true";           
            String query ="select * from Lehrer WHERE Vorname=?";
            con = DriverManager.getConnection(url,"G1", "1234"); 
            pst = con.prepareStatement(query);
                pst.setString(1,TfVornameLb.getText()); 
                  rs = pst.executeQuery();
                  if(rs.next()){
                      String sucht1=rs.getString("Vorname");
                      TfVorname.setText(sucht1);
                      String sucht2=rs.getString("Nachname");
                      TfNachname.setText(sucht2);   
                      String sucht3=rs.getString("Benutzername");
                      TfBenutzername.setText(sucht3);
                      String sucht4=rs.getString("Passwort");
                      TfPasswort.setText(sucht4);
                      String sucht5=rs.getString("Telefonnummer");
                      TfTel.setText(sucht5);
                      String sucht6=rs.getString("Email");
                      TfEmail.setText(sucht6);
                      
                  }
            }      
        catch (Exception e) { 
            JOptionPane.showMessageDialog(null,e);
       }

        // TODO add your handling code here:
    }//GEN-LAST:event_TfVornameLbKeyReleased

    private void TfNachnameLbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfNachnameLbKeyReleased
        // TODO add your handling code here:
        try {             
            Class.forName("org.hsqldb.jdbcDriver"); 
            String url = "jdbc:hsqldb:file:C:\\Users\\domin\\Desktop\\sql\\;shutdown=true";           
            String query ="select * from Lehrer WHERE Nachname=?";
            con = DriverManager.getConnection(url,"G1", "1234"); 
            pst = con.prepareStatement(query);
                pst.setString(1,TfNachnameLb.getText()); 
                  rs = pst.executeQuery();
                  if(rs.next()){
                      String sucht1=rs.getString("Vorname");
                      TfVorname.setText(sucht1);
                      String sucht2=rs.getString("Nachname");
                      TfNachname.setText(sucht2);   
                      String sucht3=rs.getString("Benutzername");
                      TfBenutzername.setText(sucht3);
                      String sucht4=rs.getString("Passwort");
                      TfPasswort.setText(sucht4);
                      String sucht5=rs.getString("Telefonnummer");
                      TfTel.setText(sucht5);
                      String sucht6=rs.getString("Email");
                      TfEmail.setText(sucht6);
                      
                  }
            }      
        catch (Exception e) { 
            JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_TfNachnameLbKeyReleased

    private void TfBenutzernameLbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfBenutzernameLbKeyReleased
        // TODO add your handling code here:
        try {             
            Class.forName("org.hsqldb.jdbcDriver"); 
            String url = "jdbc:hsqldb:file:C:\\Users\\domin\\Desktop\\sql\\;shutdown=true";           
            String query ="select * from Lehrer WHERE Benutzername=?";
            con = DriverManager.getConnection(url,"G1", "1234"); 
            pst = con.prepareStatement(query);
                pst.setString(1,TfBenutzernameLb.getText()); 
                  rs = pst.executeQuery();
                  if(rs.next()){
                      String sucht1=rs.getString("Vorname");
                      TfVorname.setText(sucht1);
                      String sucht2=rs.getString("Nachname");
                      TfNachname.setText(sucht2);   
                      String sucht3=rs.getString("Benutzername");
                      TfBenutzername.setText(sucht3);
                      String sucht4=rs.getString("Passwort");
                      TfPasswort.setText(sucht4);
                      String sucht5=rs.getString("Telefonnummer");
                      TfTel.setText(sucht5);
                      String sucht6=rs.getString("Email");
                      TfEmail.setText(sucht6);
                      
                  }
            }      
        catch (Exception e) { 
            JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_TfBenutzernameLbKeyReleased

    private void TfVornameBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfVornameBpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfVornameBpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lehrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lehrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lehrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lehrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lehrer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Benutzername;
    private javax.swing.JLabel BenutzernameBp;
    private javax.swing.JLabel BenutzernameLb;
    private javax.swing.JLabel BenutzernameLl;
    private javax.swing.JLabel BenutzernameLs;
    private javax.swing.JLabel BenutzernameSp;
    private javax.swing.JLabel EmaiBp;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EmailSp;
    private javax.swing.JTable Lehrer;
    private javax.swing.JTable Lehrer1;
    private javax.swing.JTable Lehrer2;
    private javax.swing.JPanel LehrerBearbeiten;
    private javax.swing.JPanel LehrerLöschen;
    private javax.swing.JPanel LehrerNeu;
    private javax.swing.JPanel LehrerSuchen;
    private javax.swing.JLabel Nachname;
    private javax.swing.JLabel NachnameBp;
    private javax.swing.JLabel NachnameLb;
    private javax.swing.JLabel NachnameLl;
    private javax.swing.JLabel NachnameLs;
    private javax.swing.JLabel NachnameSp;
    private javax.swing.JLabel Passwort;
    private javax.swing.JLabel PasswortBp;
    private javax.swing.JLabel PasswortSp;
    private javax.swing.JLabel Tel;
    private javax.swing.JLabel TelBp;
    private javax.swing.JLabel TelSp;
    private javax.swing.JTextField TfBenutzername;
    private javax.swing.JTextField TfBenutzernameBp;
    private javax.swing.JTextField TfBenutzernameLb;
    private javax.swing.JTextField TfBenutzernameLl;
    private javax.swing.JTextField TfBenutzernameLs;
    private javax.swing.JTextField TfBenutzernameSp;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfEmailBp;
    private javax.swing.JTextField TfEmailSp;
    private javax.swing.JTextField TfNachname;
    private javax.swing.JTextField TfNachnameBp;
    private javax.swing.JTextField TfNachnameLb;
    private javax.swing.JTextField TfNachnameLl;
    private javax.swing.JTextField TfNachnameLs;
    private javax.swing.JTextField TfNachnameSp;
    private javax.swing.JTextField TfPasswort;
    private javax.swing.JTextField TfPasswortBp;
    private javax.swing.JTextField TfPasswortSp;
    private javax.swing.JTextField TfTel;
    private javax.swing.JTextField TfTelBp;
    private javax.swing.JTextField TfTelSp;
    private javax.swing.JTextField TfVorname;
    private javax.swing.JTextField TfVornameBp;
    private javax.swing.JTextField TfVornameLb;
    private javax.swing.JTextField TfVornameLl;
    private javax.swing.JTextField TfVornameLs;
    private javax.swing.JTextField TfVornameSp;
    private javax.swing.JLabel Vorname;
    private javax.swing.JLabel VornameBp;
    private javax.swing.JLabel VornameLb;
    private javax.swing.JLabel VornameLl;
    private javax.swing.JLabel VornameLs;
    private javax.swing.JLabel VornameSp;
    private javax.swing.JButton jBLehrerEingebenLb;
    private javax.swing.JButton jBLehrerEingebenLs;
    private javax.swing.JButton jBLehrerLöschenLl;
    private javax.swing.JButton jBLehrerOkaySp;
    private javax.swing.JButton jBLehrerSpeichern;
    private javax.swing.JButton jBLehrerSpeichernBp;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLayeredPane jLayeredPaneB;
    private javax.swing.JLayeredPane jLayeredPaneS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void close() {
        
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
