/*
 * emirhan 
 */
package studentenmanagement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import studentenmanagement.Klasse.*;

public class RaumFenster extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public RaumFenster() {
        initComponents();
        initDB();
        show_Raum();
    }
    
    public void initDB() {

       try { 
           Class.forName("org.hsqldb.jdbcDriver"); 
           String url = "jdbc:hsqldb:file:C:\\Users\\domin\\Desktop\\sql\\;shutdown=true";  
           con = DriverManager.getConnection(url,"G1", "1234");
           
       }  catch (Exception e) { 
            JOptionPane.showMessageDialog(null,e);
       }
    }
    
    
    public ArrayList<Raum> RaumList(){
        
        ArrayList<Raum> r= new ArrayList<>();
        if (con != null) {
        try {
           String query ="SELECT * FROM raum";
           Statement st= con.createStatement();
           rs =st.executeQuery(query);
           Raum raum;
           while(rs.next()){
                raum = new Raum(rs.getInt("ID"), rs.getString("Name"),rs.getString("Lagebeschreibung"),rs.getInt("Kapazitat"));
                r.add(raum);
           }
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,e);
        }
        
        }
        return r;
    }
    
    public void show_Raum(){
        
        ArrayList<Raum> list = RaumList();
        DefaultTableModel model = (DefaultTableModel) raum_table.getModel();
        model.setRowCount(0);
        Object[] row = new Object[3];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getLagebeschreibung();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getKapazitat();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        raum_table = new javax.swing.JTable();
        su3 = new javax.swing.JLabel();
        such3 = new javax.swing.JTextField();
        speichern3 = new javax.swing.JButton();
        suche3 = new javax.swing.JButton();
        bearbeit3 = new javax.swing.JButton();
        lösch = new javax.swing.JButton();
        neu3 = new javax.swing.JButton();
        sname = new javax.swing.JTextField();
        slagebe = new javax.swing.JTextField();
        skapazitat = new javax.swing.JTextField();
        sID = new javax.swing.JLabel();
        svn = new javax.swing.JLabel();
        snn = new javax.swing.JLabel();
        löschen = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        lname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        raum_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Raum Name", "Lagebeschreibung", "Kapazitat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(raum_table);

        su3.setText("Suche");

        such3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                such3ActionPerformed(evt);
            }
        });
        such3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                such3KeyReleased(evt);
            }
        });

        speichern3.setBackground(new java.awt.Color(255, 204, 255));
        speichern3.setText("Speichern");
        speichern3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speichern3ActionPerformed(evt);
            }
        });

        suche3.setBackground(new java.awt.Color(255, 204, 255));
        suche3.setText("Suchen");
        suche3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suche3ActionPerformed(evt);
            }
        });

        bearbeit3.setBackground(new java.awt.Color(153, 0, 153));
        bearbeit3.setForeground(new java.awt.Color(255, 255, 255));
        bearbeit3.setText("Bearbeiten");
        bearbeit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bearbeit3ActionPerformed(evt);
            }
        });

        lösch.setBackground(new java.awt.Color(0, 102, 204));
        lösch.setForeground(new java.awt.Color(255, 255, 255));
        lösch.setText("Löschen");
        lösch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                löschActionPerformed(evt);
            }
        });

        neu3.setBackground(new java.awt.Color(102, 204, 255));
        neu3.setText("Neu");
        neu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neu3ActionPerformed(evt);
            }
        });

        sID.setText("Raum Name");

        svn.setText("Lagebeschreibung");

        snn.setText("Kapazitat");

        löschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                löschenActionPerformed(evt);
            }
        });

        id_label.setText("ID");

        sid.setEditable(false);

        lname.setText("Raum Name");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(su3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(such3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suche3)
                                .addGap(0, 60, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(id_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(neu3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(speichern3))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(sID)
                                            .addComponent(snn)
                                            .addComponent(svn))))
                                .addGap(5, 5, 5)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skapazitat, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(slagebe, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(392, 392, 392))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(löschen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(bearbeit3)
                                .addGap(190, 190, 190)
                                .addComponent(lösch)))
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(su3)
                    .addComponent(such3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suche3))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_label))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slagebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skapazitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snn))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(löschen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lösch)
                    .addComponent(bearbeit3)
                    .addComponent(speichern3)
                    .addComponent(neu3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void neu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neu3ActionPerformed

        slagebe.setText("");
        sname.setText("");
        skapazitat.setText("");
        sid.setText("");
        such3.setText("");
        löschen.setText("");
    }//GEN-LAST:event_neu3ActionPerformed

    private void löschActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_löschActionPerformed
        if (con != null) {
            int onay = JOptionPane.showConfirmDialog(null, "Sind Sie sicher?", "raum", JOptionPane.YES_NO_OPTION);

            if (onay == 0) {

                try{
                    String query ="DELETE FROM raum WHERE NAME =?";
                    pst = con.prepareStatement(query);
                    pst.setString(1,löschen.getText());
                    pst.executeUpdate();
                    
                    show_Raum();
                    JOptionPane.showMessageDialog(null,"Gelöscht!");
                } catch (Exception ex) {
                    System.out.println(ex);
                    JOptionPane.showMessageDialog(null, "Nicht Gelöscht!");
                }

            } else {

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_löschActionPerformed

    private void bearbeit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bearbeit3ActionPerformed
        if (con != null) {
            try {
                String query ="UPDATE raum SET Name=?, Lagebeschreibung=?, Kapazitat=?  WHERE ID=?";
                pst = con.prepareStatement(query);

                pst.setString(1,sname.getText());
                pst.setString(2,slagebe.getText());
                pst.setInt(3,Integer.parseInt(skapazitat.getText()));
                pst.setInt(4,Integer.parseInt(sid.getText()));
                pst.executeUpdate();
                
                show_Raum();

            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Nicht Bearbeitet!");
            }
        }
    }//GEN-LAST:event_bearbeit3ActionPerformed

    private void suche3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suche3ActionPerformed
        if (con != null) {
            try {                       
                String query ="select * from raum WHERE NAME=?";
                pst = con.prepareStatement(query);
                pst.setString(1,such3.getText()); 

                rs = pst.executeQuery();
                if (rs.next()){
                          slagebe.setText(rs.getString("Lagebeschreibung"));
                          sname.setText(rs.getString("Name"));
                          skapazitat.setText("" + rs.getInt("Kapazitat"));
                          sid.setText("" + rs.getInt("ID"));
                }
            } catch (Exception e) { 
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_suche3ActionPerformed

    private void speichern3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speichern3ActionPerformed
        if (con != null) {
            try {
                String query ="insert into raum"
                +" (Lagebeschreibung,Name,Kapazitat)"
                +" values(?,?,?)";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1,slagebe.getText());
                pst.setString(2,sname.getText());
                pst.setInt(3,Integer.parseInt(skapazitat.getText()));
                pst.executeUpdate();
                
                show_Raum();
                JOptionPane.showMessageDialog(null,"Gespeichert!");
            }
            catch (SQLException e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null,"Sie haben sich falsch angemeldet!");
            }
        }
    }//GEN-LAST:event_speichern3ActionPerformed

    private void such3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_such3KeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_such3KeyReleased

    private void such3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_such3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_such3ActionPerformed

    private void löschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_löschenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_löschenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaumFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaumFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaumFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaumFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RaumFenster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bearbeit3;
    private javax.swing.JLabel id_label;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lname;
    private javax.swing.JButton lösch;
    private javax.swing.JTextField löschen;
    private javax.swing.JButton neu3;
    private javax.swing.JTable raum_table;
    private javax.swing.JLabel sID;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField skapazitat;
    private javax.swing.JTextField slagebe;
    private javax.swing.JTextField sname;
    private javax.swing.JLabel snn;
    private javax.swing.JButton speichern3;
    private javax.swing.JLabel su3;
    private javax.swing.JTextField such3;
    private javax.swing.JButton suche3;
    private javax.swing.JLabel svn;
    // End of variables declaration//GEN-END:variables
}
