/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentenmanagement;

/**
 *
 * @author Asus
 */
public class Raum extends javax.swing.JFrame {

    /**
     * Creates new form Raum
     */
    public Raum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        NeuRaum = new javax.swing.JPanel();
        LageBeschreibung = new javax.swing.JLabel();
        RaumName = new javax.swing.JLabel();
        Kapazitaet = new javax.swing.JLabel();
        TfLageBescreibung = new javax.swing.JTextField();
        TfRaumName = new javax.swing.JTextField();
        TfKapazitaet = new javax.swing.JTextField();
        BtSpeichernNr = new javax.swing.JButton();
        RaumFach = new javax.swing.JLabel();
        TfRaumFachNr = new javax.swing.JTextField();
        RaumLöschen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TfRaumNameRl = new javax.swing.JTextField();
        BtLoeschenRl = new javax.swing.JButton();
        RaumSuchen = new javax.swing.JPanel();
        RaumNameRs = new javax.swing.JLabel();
        TfRaumSuchen = new javax.swing.JTextField();
        BtSuchenRs = new javax.swing.JButton();
        RaumBearbeiten = new javax.swing.JPanel();
        RaumNameRb = new javax.swing.JLabel();
        TfRaumNameRb = new javax.swing.JTextField();
        jScrollPaneRb = new javax.swing.JScrollPane();
        jListRb = new javax.swing.JList<>();
        jLayeredPaneRb = new javax.swing.JLayeredPane();
        LageBeschreibungRb = new javax.swing.JLabel();
        KapazitaetRb = new javax.swing.JLabel();
        RaumFachRb = new javax.swing.JLabel();
        TfRaumFachRb = new javax.swing.JTextField();
        TfKapazitaetRb = new javax.swing.JTextField();
        TfLageBescreibungRb = new javax.swing.JTextField();
        BtSpeichernRb = new javax.swing.JButton();
        BtAuswaehlenRb = new javax.swing.JButton();
        BtSuchenRb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LageBeschreibung.setText("Lage Beschreibung");

        RaumName.setText("Raum Name");

        Kapazitaet.setText("Kapazität");

        BtSpeichernNr.setText("Speichern");

        RaumFach.setText("Raum Fach");

        javax.swing.GroupLayout NeuRaumLayout = new javax.swing.GroupLayout(NeuRaum);
        NeuRaum.setLayout(NeuRaumLayout);
        NeuRaumLayout.setHorizontalGroup(
            NeuRaumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NeuRaumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtSpeichernNr)
                .addGap(25, 25, 25))
            .addGroup(NeuRaumLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(NeuRaumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LageBeschreibung)
                    .addComponent(RaumName)
                    .addComponent(Kapazitaet)
                    .addComponent(RaumFach))
                .addGap(56, 56, 56)
                .addGroup(NeuRaumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfRaumFachNr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NeuRaumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TfKapazitaet, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(TfRaumName)
                        .addComponent(TfLageBescreibung)))
                .addContainerGap(456, Short.MAX_VALUE))
        );
        NeuRaumLayout.setVerticalGroup(
            NeuRaumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NeuRaumLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(NeuRaumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LageBeschreibung)
                    .addComponent(TfLageBescreibung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NeuRaumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RaumName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfRaumName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NeuRaumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kapazitaet)
                    .addComponent(TfKapazitaet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NeuRaumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfRaumFachNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RaumFach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(BtSpeichernNr)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Neu Raum", NeuRaum);

        jLabel2.setText("Raum Name");

        BtLoeschenRl.setText("Löschen");

        javax.swing.GroupLayout RaumLöschenLayout = new javax.swing.GroupLayout(RaumLöschen);
        RaumLöschen.setLayout(RaumLöschenLayout);
        RaumLöschenLayout.setHorizontalGroup(
            RaumLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaumLöschenLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(89, 89, 89)
                .addComponent(TfRaumNameRl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RaumLöschenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtLoeschenRl)
                .addGap(43, 43, 43))
        );
        RaumLöschenLayout.setVerticalGroup(
            RaumLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaumLöschenLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(RaumLöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TfRaumNameRl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(BtLoeschenRl)
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Raum Löschen", RaumLöschen);

        RaumNameRs.setText("Raum Name");

        BtSuchenRs.setText("Suchen");

        javax.swing.GroupLayout RaumSuchenLayout = new javax.swing.GroupLayout(RaumSuchen);
        RaumSuchen.setLayout(RaumSuchenLayout);
        RaumSuchenLayout.setHorizontalGroup(
            RaumSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaumSuchenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtSuchenRs)
                .addGap(18, 18, 18))
            .addGroup(RaumSuchenLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(RaumNameRs)
                .addGap(67, 67, 67)
                .addComponent(TfRaumSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 445, Short.MAX_VALUE))
        );
        RaumSuchenLayout.setVerticalGroup(
            RaumSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaumSuchenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(RaumSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RaumNameRs)
                    .addComponent(TfRaumSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(BtSuchenRs)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Raum Suchen", RaumSuchen);

        RaumNameRb.setText("Raum Name");

        jListRb.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneRb.setViewportView(jListRb);

        LageBeschreibungRb.setText("Lage Beschreibung");

        KapazitaetRb.setText("Kapazität");

        RaumFachRb.setText("Raum Fach");

        TfRaumFachRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfRaumFachRbActionPerformed(evt);
            }
        });

        BtSpeichernRb.setText("Speichern");
        BtSpeichernRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSpeichernRbActionPerformed(evt);
            }
        });

        jLayeredPaneRb.setLayer(LageBeschreibungRb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRb.setLayer(KapazitaetRb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRb.setLayer(RaumFachRb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRb.setLayer(TfRaumFachRb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRb.setLayer(TfKapazitaetRb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRb.setLayer(TfLageBescreibungRb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRb.setLayer(BtSpeichernRb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneRbLayout = new javax.swing.GroupLayout(jLayeredPaneRb);
        jLayeredPaneRb.setLayout(jLayeredPaneRbLayout);
        jLayeredPaneRbLayout.setHorizontalGroup(
            jLayeredPaneRbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneRbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneRbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPaneRbLayout.createSequentialGroup()
                        .addGroup(jLayeredPaneRbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RaumFachRb)
                            .addComponent(KapazitaetRb))
                        .addGap(55, 55, 55)
                        .addGroup(jLayeredPaneRbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TfKapazitaetRb, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(TfRaumFachRb)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneRbLayout.createSequentialGroup()
                        .addComponent(LageBeschreibungRb)
                        .addGap(18, 18, 18)
                        .addComponent(TfLageBescreibungRb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(BtSpeichernRb)
                .addGap(18, 18, 18))
        );
        jLayeredPaneRbLayout.setVerticalGroup(
            jLayeredPaneRbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneRbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneRbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KapazitaetRb)
                    .addComponent(TfKapazitaetRb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jLayeredPaneRbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RaumFachRb)
                    .addComponent(TfRaumFachRb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jLayeredPaneRbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LageBeschreibungRb)
                    .addComponent(TfLageBescreibungRb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneRbLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtSpeichernRb))
        );

        BtAuswaehlenRb.setText("Auswählen");

        BtSuchenRb.setText("Suchen");
        BtSuchenRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSuchenRbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RaumBearbeitenLayout = new javax.swing.GroupLayout(RaumBearbeiten);
        RaumBearbeiten.setLayout(RaumBearbeitenLayout);
        RaumBearbeitenLayout.setHorizontalGroup(
            RaumBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaumBearbeitenLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(RaumBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RaumBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtAuswaehlenRb)
                        .addGroup(RaumBearbeitenLayout.createSequentialGroup()
                            .addGroup(RaumBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(RaumBearbeitenLayout.createSequentialGroup()
                                    .addComponent(RaumNameRb)
                                    .addGap(52, 52, 52)
                                    .addComponent(TfRaumNameRb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(BtSuchenRb))
                            .addGap(157, 157, 157)
                            .addComponent(jScrollPaneRb, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLayeredPaneRb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        RaumBearbeitenLayout.setVerticalGroup(
            RaumBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaumBearbeitenLayout.createSequentialGroup()
                .addGroup(RaumBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RaumBearbeitenLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(RaumBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RaumNameRb)
                            .addComponent(TfRaumNameRb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(BtSuchenRb))
                    .addGroup(RaumBearbeitenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneRb, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(BtAuswaehlenRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLayeredPaneRb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Raum Bearbeiten", RaumBearbeiten);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfRaumFachRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfRaumFachRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfRaumFachRbActionPerformed

    private void BtSpeichernRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSpeichernRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtSpeichernRbActionPerformed

    private void BtSuchenRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSuchenRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtSuchenRbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Raum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Raum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Raum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Raum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Raum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAuswaehlenRb;
    private javax.swing.JButton BtLoeschenRl;
    private javax.swing.JButton BtSpeichernNr;
    private javax.swing.JButton BtSpeichernRb;
    private javax.swing.JButton BtSuchenRb;
    private javax.swing.JButton BtSuchenRs;
    private javax.swing.JLabel Kapazitaet;
    private javax.swing.JLabel KapazitaetRb;
    private javax.swing.JLabel LageBeschreibung;
    private javax.swing.JLabel LageBeschreibungRb;
    private javax.swing.JPanel NeuRaum;
    private javax.swing.JPanel RaumBearbeiten;
    private javax.swing.JLabel RaumFach;
    private javax.swing.JLabel RaumFachRb;
    private javax.swing.JPanel RaumLöschen;
    private javax.swing.JLabel RaumName;
    private javax.swing.JLabel RaumNameRb;
    private javax.swing.JLabel RaumNameRs;
    private javax.swing.JPanel RaumSuchen;
    private javax.swing.JTextField TfKapazitaet;
    private javax.swing.JTextField TfKapazitaetRb;
    private javax.swing.JTextField TfLageBescreibung;
    private javax.swing.JTextField TfLageBescreibungRb;
    private javax.swing.JTextField TfRaumFachNr;
    private javax.swing.JTextField TfRaumFachRb;
    private javax.swing.JTextField TfRaumName;
    private javax.swing.JTextField TfRaumNameRb;
    private javax.swing.JTextField TfRaumNameRl;
    private javax.swing.JTextField TfRaumSuchen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPaneRb;
    private javax.swing.JList<String> jListRb;
    private javax.swing.JScrollPane jScrollPaneRb;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
