/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentenmanagement;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author mertcenk
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        StudentKlasseZuteilen = new javax.swing.JPanel();
        StudentNeu = new javax.swing.JPanel();
        Vorname = new javax.swing.JLabel();
        Nachname = new javax.swing.JLabel();
        TC = new javax.swing.JLabel();
        GebTag = new javax.swing.JLabel();
        GebJahr = new javax.swing.JLabel();
        Geschlecht = new javax.swing.JLabel();
        PLZ = new javax.swing.JLabel();
        Ort = new javax.swing.JLabel();
        Bezirk = new javax.swing.JLabel();
        Strasse = new javax.swing.JLabel();
        Hausnummer = new javax.swing.JLabel();
        Tel = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        TfVorname = new javax.swing.JTextField();
        TfNachname = new javax.swing.JTextField();
        TfTC = new javax.swing.JTextField();
        TfGeschlecht = new javax.swing.JTextField();
        TfPLZ = new javax.swing.JTextField();
        TfOrt = new javax.swing.JTextField();
        TfBezirk = new javax.swing.JTextField();
        TfStrasse = new javax.swing.JTextField();
        TfHausnummer = new javax.swing.JTextField();
        TfTel = new javax.swing.JTextField();
        TfEmail = new javax.swing.JTextField();
        Schuleintrittsart = new javax.swing.JLabel();
        Schuleintrittsnote = new javax.swing.JLabel();
        Schuleintrittsreihe = new javax.swing.JLabel();
        Fremdsprache = new javax.swing.JLabel();
        Fach = new javax.swing.JLabel();
        Praferenzreihenfolge = new javax.swing.JLabel();
        Kontingent = new javax.swing.JLabel();
        Klasse = new javax.swing.JLabel();
        Elternvertreter = new javax.swing.JLabel();
        VornameErziehungsberechtigter = new javax.swing.JLabel();
        TfSchuleintrittsart = new javax.swing.JTextField();
        TfSchuleintrittsnote = new javax.swing.JTextField();
        TfSchuleintrittsreihe = new javax.swing.JTextField();
        TfFremdsprache = new javax.swing.JTextField();
        TfFach = new javax.swing.JTextField();
        TfPraferenzreihenfolge = new javax.swing.JTextField();
        TfKontingent = new javax.swing.JTextField();
        TfKlasse = new javax.swing.JTextField();
        TfElternvertreter = new javax.swing.JTextField();
        TfVornameErziehungsberechtigter = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        Studentbearbeiten = new javax.swing.JPanel();
        VornameSb = new javax.swing.JLabel();
        NachnameSb = new javax.swing.JLabel();
        MatrikelnummerSb = new javax.swing.JLabel();
        TfVornameSb = new javax.swing.JTextField();
        TfNachnameSb = new javax.swing.JTextField();
        TfMatrikelnummerSb = new javax.swing.JTextField();
        JbAuswahlenSb = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Vorname1 = new javax.swing.JLabel();
        TfPLZ1Sb = new javax.swing.JTextField();
        Nachname1 = new javax.swing.JLabel();
        TfOrt1Sb = new javax.swing.JTextField();
        TC1 = new javax.swing.JLabel();
        TfBezirk1Sb = new javax.swing.JTextField();
        Geburtsdatum = new javax.swing.JLabel();
        TfStrasse1Sb = new javax.swing.JTextField();
        Klasse1 = new javax.swing.JLabel();
        Elternvertreter1 = new javax.swing.JLabel();
        VornameErziehungsberechtigter1 = new javax.swing.JLabel();
        TfSchuleintrittsart1Sb = new javax.swing.JTextField();
        TfSchuleintrittsnote1Sb = new javax.swing.JTextField();
        TfSchuleintrittsreihe1Sb = new javax.swing.JTextField();
        TfFremdsprache1Sb = new javax.swing.JTextField();
        TfFach1Sb = new javax.swing.JTextField();
        TfPraferenzreihenfolge1Sb = new javax.swing.JTextField();
        TfHausnummer1Sb = new javax.swing.JTextField();
        TfTel1Sb = new javax.swing.JTextField();
        Geschlecht1 = new javax.swing.JLabel();
        TfEmail1Sb = new javax.swing.JTextField();
        PLZ1 = new javax.swing.JLabel();
        Ort1 = new javax.swing.JLabel();
        Bezirk1 = new javax.swing.JLabel();
        Strasse1 = new javax.swing.JLabel();
        Hausnummer1 = new javax.swing.JLabel();
        Tel1 = new javax.swing.JLabel();
        Email1 = new javax.swing.JLabel();
        TfVorname1Sb = new javax.swing.JTextField();
        TfKontingent1Sb = new javax.swing.JTextField();
        TfKlasse1Sb = new javax.swing.JTextField();
        TfElternvertreter1Sb = new javax.swing.JTextField();
        TfVornameErziehungsberechtigter1Sb = new javax.swing.JTextField();
        Schuleintrittsart1 = new javax.swing.JLabel();
        Schuleintrittsnote1 = new javax.swing.JLabel();
        Schuleintrittsreihe1 = new javax.swing.JLabel();
        Fremdsprache1 = new javax.swing.JLabel();
        Fach1 = new javax.swing.JLabel();
        Praferenzreihenfolge1 = new javax.swing.JLabel();
        Kontingent1 = new javax.swing.JLabel();
        TfNachname1Sb = new javax.swing.JTextField();
        TfTC1Sb = new javax.swing.JTextField();
        TfGebTag1Sb = new javax.swing.JTextField();
        TfGeschlecht1Sb = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Studentsuchen = new javax.swing.JPanel();
        VornameSs = new javax.swing.JLabel();
        NachnameSs = new javax.swing.JLabel();
        MatrikelnummerSs = new javax.swing.JLabel();
        TfVornameSs = new javax.swing.JTextField();
        TfNachnameSs = new javax.swing.JTextField();
        TfMatrikelnummerSs = new javax.swing.JTextField();
        BtSuchenSs = new javax.swing.JButton();
        Vorname2Ss = new javax.swing.JLabel();
        Nachname2Ss = new javax.swing.JLabel();
        Matrikelnummer2Ss = new javax.swing.JLabel();
        TfVorname2Ss = new javax.swing.JTextField();
        TfNachname2Ss = new javax.swing.JTextField();
        TfMatrikelnummer2Ss = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Studentlöschen = new javax.swing.JPanel();
        VornameSl = new javax.swing.JLabel();
        NachnameSl = new javax.swing.JLabel();
        MatrikelnummerSl = new javax.swing.JLabel();
        TfVornameSl = new javax.swing.JTextField();
        TfNachnameSl = new javax.swing.JTextField();
        TfMatrikelnummerSl = new javax.swing.JTextField();
        BtlöschenSl = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Vorname.setText("Vorname");

        Nachname.setText("Nachname");

        TC.setText("TC");

        GebJahr.setText("Geburtsdatum");

        Geschlecht.setText("Geschlecht");

        PLZ.setText("PLZ");

        Ort.setText("Ort");

        Bezirk.setText("Bezirk");

        Strasse.setText("Strasse");

        Hausnummer.setText("Hausnummer");

        Tel.setText("Telefonnummer");

        Email.setText("Email");

        TfTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfTelActionPerformed(evt);
            }
        });

        Schuleintrittsart.setText("Schuleintrittsart");

        Schuleintrittsnote.setText("Schuleintrittsnote");

        Schuleintrittsreihe.setText("Schuleintrittsreihe");

        Fremdsprache.setText("Fremdsprache");

        Fach.setText("Fach");

        Praferenzreihenfolge.setText("Prafeferenzreihenfolge");

        Kontingent.setText("Kontingent");

        Klasse.setText("Klasse");

        Elternvertreter.setText("Elternvertreter");

        VornameErziehungsberechtigter.setText("VornameErziehungsberechtigter");

        jButton1.setBackground(new java.awt.Color(255, 153, 255));
        jButton1.setText("Speichern");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentNeuLayout = new javax.swing.GroupLayout(StudentNeu);
        StudentNeu.setLayout(StudentNeuLayout);
        StudentNeuLayout.setHorizontalGroup(
            StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentNeuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(StudentNeuLayout.createSequentialGroup()
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Vorname)
                            .addComponent(Nachname)
                            .addComponent(TC)
                            .addComponent(GebTag)
                            .addComponent(Geschlecht)
                            .addComponent(PLZ)
                            .addComponent(Ort)
                            .addComponent(Bezirk)
                            .addComponent(Strasse)
                            .addComponent(Hausnummer)
                            .addComponent(Email)
                            .addComponent(Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GebJahr, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TfTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(TfHausnummer, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfStrasse, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfBezirk, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfOrt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfPLZ, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfGeschlecht, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfTC, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfNachname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfEmail)
                                .addComponent(TfVorname, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(153, 153, 153)
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(StudentNeuLayout.createSequentialGroup()
                                .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Schuleintrittsart)
                                    .addComponent(Schuleintrittsnote)
                                    .addComponent(Schuleintrittsreihe)
                                    .addComponent(Fremdsprache)
                                    .addComponent(Fach)
                                    .addComponent(Praferenzreihenfolge)
                                    .addComponent(Kontingent)
                                    .addComponent(Klasse)
                                    .addComponent(Elternvertreter))
                                .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(StudentNeuLayout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(TfElternvertreter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentNeuLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TfKontingent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TfPraferenzreihenfolge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TfFach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TfFremdsprache, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TfSchuleintrittsreihe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TfSchuleintrittsnote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TfSchuleintrittsart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(TfKlasse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StudentNeuLayout.createSequentialGroup()
                                .addComponent(VornameErziehungsberechtigter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TfVornameErziehungsberechtigter)))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        StudentNeuLayout.setVerticalGroup(
            StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentNeuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vorname)
                    .addComponent(TfVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Schuleintrittsart)
                    .addComponent(TfSchuleintrittsart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nachname)
                    .addComponent(TfNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Schuleintrittsnote)
                    .addComponent(TfSchuleintrittsnote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfSchuleintrittsreihe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TC)
                        .addComponent(TfTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Schuleintrittsreihe)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentNeuLayout.createSequentialGroup()
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GebTag)
                            .addComponent(Fremdsprache)
                            .addComponent(TfFremdsprache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GebJahr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fach)
                            .addComponent(TfFach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Geschlecht)
                            .addComponent(TfGeschlecht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Praferenzreihenfolge)
                            .addComponent(TfPraferenzreihenfolge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PLZ)
                            .addComponent(TfPLZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Kontingent)
                            .addComponent(TfKontingent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ort)
                            .addComponent(TfOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Klasse)
                            .addComponent(TfKlasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bezirk)
                            .addComponent(TfBezirk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Elternvertreter)
                            .addComponent(TfElternvertreter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Strasse)
                            .addComponent(TfStrasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hausnummer)
                            .addComponent(TfHausnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VornameErziehungsberechtigter)
                            .addComponent(TfVornameErziehungsberechtigter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tel)
                            .addComponent(TfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(StudentNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email)
                            .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout StudentKlasseZuteilenLayout = new javax.swing.GroupLayout(StudentKlasseZuteilen);
        StudentKlasseZuteilen.setLayout(StudentKlasseZuteilenLayout);
        StudentKlasseZuteilenLayout.setHorizontalGroup(
            StudentKlasseZuteilenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentKlasseZuteilenLayout.createSequentialGroup()
                .addComponent(StudentNeu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        StudentKlasseZuteilenLayout.setVerticalGroup(
            StudentKlasseZuteilenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentKlasseZuteilenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StudentNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Student einfügen", StudentKlasseZuteilen);

        VornameSb.setText("Vorname");

        NachnameSb.setText("Nachname");

        MatrikelnummerSb.setText("Matrikelnummer");

        JbAuswahlenSb.setText("Auswahlen");

        Vorname1.setText("Vorname");

        Nachname1.setText("Nachname");

        TC1.setText("TC");

        Geburtsdatum.setText("Geburtsdatum");

        Klasse1.setText("Klasse");

        Elternvertreter1.setText("Elternvertreter");

        VornameErziehungsberechtigter1.setText("VornameErziehungsberechtigter");

        Geschlecht1.setText("Geschlecht");

        PLZ1.setText("PLZ");

        Ort1.setText("Ort");

        Bezirk1.setText("Bezirk");

        Strasse1.setText("Strasse");

        Hausnummer1.setText("Hausnummer");

        Tel1.setText("Telefonnummer");

        Email1.setText("Email");

        Schuleintrittsart1.setText("Schuleintrittsart");

        Schuleintrittsnote1.setText("Schuleintrittsnote");

        Schuleintrittsreihe1.setText("Schuleintrittsreihe");

        Fremdsprache1.setText("Fremdsprache");

        Fach1.setText("Fach");

        Praferenzreihenfolge1.setText("Prafeferenzreihenfolge");

        Kontingent1.setText("Kontingent");

        TfGebTag1Sb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfGebTag1SbActionPerformed(evt);
            }
        });

        jButton2.setText("Okay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(Vorname1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfPLZ1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Nachname1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfOrt1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TC1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfBezirk1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Geburtsdatum, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfStrasse1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Klasse1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Elternvertreter1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(VornameErziehungsberechtigter1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfSchuleintrittsart1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfSchuleintrittsnote1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfSchuleintrittsreihe1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfFremdsprache1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfFach1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfPraferenzreihenfolge1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfHausnummer1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfTel1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Geschlecht1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfEmail1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PLZ1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Ort1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Bezirk1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Strasse1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Hausnummer1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Tel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Email1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfVorname1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfKontingent1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfKlasse1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfElternvertreter1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfVornameErziehungsberechtigter1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Schuleintrittsart1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Schuleintrittsnote1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Schuleintrittsreihe1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Fremdsprache1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Fach1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Praferenzreihenfolge1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Kontingent1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfNachname1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfTC1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfGebTag1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TfGeschlecht1Sb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Vorname1)
                    .addComponent(Nachname1)
                    .addComponent(TC1)
                    .addComponent(Geburtsdatum)
                    .addComponent(Geschlecht1)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Ort1)
                        .addComponent(PLZ1))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Strasse1)
                            .addComponent(Bezirk1)
                            .addComponent(Tel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hausnummer1)
                            .addComponent(Email1))))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfBezirk1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TfVorname1Sb, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addComponent(TfNachname1Sb)
                        .addComponent(TfTC1Sb)
                        .addComponent(TfGebTag1Sb)
                        .addComponent(TfGeschlecht1Sb)
                        .addComponent(TfPLZ1Sb)
                        .addComponent(TfOrt1Sb)
                        .addComponent(TfStrasse1Sb)
                        .addComponent(TfHausnummer1Sb)
                        .addComponent(TfTel1Sb)
                        .addComponent(TfEmail1Sb)))
                .addGap(64, 64, 64)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(VornameErziehungsberechtigter1)
                        .addGap(32, 32, 32)
                        .addComponent(TfVornameErziehungsberechtigter1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Schuleintrittsart1)
                            .addComponent(Schuleintrittsnote1)
                            .addComponent(Schuleintrittsreihe1)
                            .addComponent(Fremdsprache1)
                            .addComponent(Fach1)
                            .addComponent(Praferenzreihenfolge1)
                            .addComponent(Kontingent1)
                            .addComponent(Klasse1)
                            .addComponent(Elternvertreter1))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(TfElternvertreter1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfKontingent1Sb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfPraferenzreihenfolge1Sb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfFach1Sb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfFremdsprache1Sb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfSchuleintrittsreihe1Sb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfSchuleintrittsnote1Sb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfSchuleintrittsart1Sb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(TfKlasse1Sb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vorname1)
                    .addComponent(TfVorname1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Schuleintrittsart1)
                    .addComponent(TfSchuleintrittsart1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nachname1)
                    .addComponent(TfNachname1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Schuleintrittsnote1)
                    .addComponent(TfSchuleintrittsnote1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TC1)
                    .addComponent(TfTC1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Schuleintrittsreihe1)
                    .addComponent(TfSchuleintrittsreihe1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Geburtsdatum)
                    .addComponent(TfGebTag1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fremdsprache1)
                    .addComponent(TfFremdsprache1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fach1)
                    .addComponent(TfFach1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Geschlecht1)
                    .addComponent(TfGeschlecht1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Praferenzreihenfolge1)
                    .addComponent(TfPraferenzreihenfolge1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PLZ1)
                    .addComponent(TfPLZ1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kontingent1)
                    .addComponent(TfKontingent1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ort1)
                    .addComponent(TfOrt1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Klasse1)
                    .addComponent(TfKlasse1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bezirk1)
                    .addComponent(TfBezirk1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Elternvertreter1)
                    .addComponent(TfElternvertreter1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Strasse1)
                    .addComponent(TfStrasse1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VornameErziehungsberechtigter1)
                    .addComponent(TfVornameErziehungsberechtigter1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tel1)
                    .addComponent(TfTel1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hausnummer1)
                    .addComponent(TfHausnummer1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email1)
                    .addComponent(TfEmail1Sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jButton2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jButton3.setText("Suchen");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matrikelnummer", "Vorname", "Nachname", "Fach"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        javax.swing.GroupLayout StudentbearbeitenLayout = new javax.swing.GroupLayout(Studentbearbeiten);
        Studentbearbeiten.setLayout(StudentbearbeitenLayout);
        StudentbearbeitenLayout.setHorizontalGroup(
            StudentbearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentbearbeitenLayout.createSequentialGroup()
                .addGroup(StudentbearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StudentbearbeitenLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(StudentbearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StudentbearbeitenLayout.createSequentialGroup()
                                .addGroup(StudentbearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VornameSb)
                                    .addComponent(NachnameSb)
                                    .addComponent(MatrikelnummerSb))
                                .addGap(34, 34, 34)
                                .addGroup(StudentbearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TfNachnameSb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfVornameSb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfMatrikelnummerSb, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton3))
                        .addGap(71, 71, 71)
                        .addGroup(StudentbearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbAuswahlenSb))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        StudentbearbeitenLayout.setVerticalGroup(
            StudentbearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentbearbeitenLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(StudentbearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentbearbeitenLayout.createSequentialGroup()
                        .addGroup(StudentbearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VornameSb)
                            .addComponent(TfVornameSb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentbearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NachnameSb)
                            .addComponent(TfNachnameSb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentbearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MatrikelnummerSb)
                            .addComponent(TfMatrikelnummerSb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addComponent(jButton3))
                    .addGroup(StudentbearbeitenLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(JbAuswahlenSb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student bearbeiten", Studentbearbeiten);

        VornameSs.setText("Vorname");

        NachnameSs.setText("Nachname");

        MatrikelnummerSs.setText("Matrikelnummer");

        TfNachnameSs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNachnameSsActionPerformed(evt);
            }
        });

        BtSuchenSs.setText("Suchen");

        Vorname2Ss.setText("Vorname");

        Nachname2Ss.setText("Nachname");

        Matrikelnummer2Ss.setText("Matrikelnummer");

        jButton4.setText("Okay");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matrikelnummer", "Vorname", "Nachname", "Fach"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matrikelnummer", "Vorname", "Nachname", "Fach"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable3);

        javax.swing.GroupLayout StudentsuchenLayout = new javax.swing.GroupLayout(Studentsuchen);
        Studentsuchen.setLayout(StudentsuchenLayout);
        StudentsuchenLayout.setHorizontalGroup(
            StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentsuchenLayout.createSequentialGroup()
                .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StudentsuchenLayout.createSequentialGroup()
                        .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StudentsuchenLayout.createSequentialGroup()
                                .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NachnameSs)
                                    .addComponent(MatrikelnummerSs)
                                    .addComponent(VornameSs, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TfMatrikelnummerSs, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfNachnameSs, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfVornameSs, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentsuchenLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(StudentsuchenLayout.createSequentialGroup()
                                        .addComponent(Matrikelnummer2Ss)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                                        .addComponent(TfMatrikelnummer2Ss, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentsuchenLayout.createSequentialGroup()
                                        .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Nachname2Ss)
                                            .addComponent(Vorname2Ss, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                                        .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TfNachname2Ss, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(TfVorname2Ss))))))
                        .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentsuchenLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentsuchenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(StudentsuchenLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addComponent(BtSuchenSs))))
                .addGap(97, 97, 97))
        );
        StudentsuchenLayout.setVerticalGroup(
            StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsuchenLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentsuchenLayout.createSequentialGroup()
                        .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VornameSs)
                            .addComponent(TfVornameSs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NachnameSs)
                            .addComponent(TfNachnameSs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MatrikelnummerSs)
                            .addComponent(TfMatrikelnummerSs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentsuchenLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TfVorname2Ss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Vorname2Ss))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nachname2Ss)
                            .addComponent(TfNachname2Ss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentsuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Matrikelnummer2Ss)
                            .addComponent(TfMatrikelnummer2Ss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(StudentsuchenLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(BtSuchenSs)
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addComponent(jButton4)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student suchen", Studentsuchen);

        VornameSl.setText("Vorname");

        NachnameSl.setText("Nachname");

        MatrikelnummerSl.setText("Matrikelnummer");

        TfMatrikelnummerSl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfMatrikelnummerSlActionPerformed(evt);
            }
        });

        BtlöschenSl.setText("Löschen");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matrikelnummer", "Vorname", "Nachname", "Fach"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable4);

        javax.swing.GroupLayout StudentlöschenLayout = new javax.swing.GroupLayout(Studentlöschen);
        Studentlöschen.setLayout(StudentlöschenLayout);
        StudentlöschenLayout.setHorizontalGroup(
            StudentlöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentlöschenLayout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addGroup(StudentlöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtlöschenSl)
                    .addGroup(StudentlöschenLayout.createSequentialGroup()
                        .addGroup(StudentlöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MatrikelnummerSl)
                            .addComponent(VornameSl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NachnameSl, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addGroup(StudentlöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TfVornameSl, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(TfNachnameSl)
                            .addComponent(TfMatrikelnummerSl))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );
        StudentlöschenLayout.setVerticalGroup(
            StudentlöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentlöschenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(StudentlöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentlöschenLayout.createSequentialGroup()
                        .addGroup(StudentlöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VornameSl)
                            .addComponent(TfVornameSl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentlöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NachnameSl)
                            .addComponent(TfNachnameSl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentlöschenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MatrikelnummerSl)
                            .addComponent(TfMatrikelnummerSl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(BtlöschenSl)
                .addContainerGap(610, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student löschen", Studentlöschen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane1)
                .addGap(163, 163, 163))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfTelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TfMatrikelnummerSlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfMatrikelnummerSlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfMatrikelnummerSlActionPerformed

    private void TfNachnameSsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNachnameSsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNachnameSsActionPerformed

    private void TfGebTag1SbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfGebTag1SbActionPerformed
       String txtDate = new SimpleDateFormat ("dd/MM/yyyy").format(new Date());
     Geburtsdatum.setText(txtDate);
     // TODO add your handling code here:
    }//GEN-LAST:event_TfGebTag1SbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bezirk;
    private javax.swing.JLabel Bezirk1;
    private javax.swing.JButton BtSuchenSs;
    private javax.swing.JButton BtlöschenSl;
    private javax.swing.JLabel Elternvertreter;
    private javax.swing.JLabel Elternvertreter1;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JLabel Fach;
    private javax.swing.JLabel Fach1;
    private javax.swing.JLabel Fremdsprache;
    private javax.swing.JLabel Fremdsprache1;
    private javax.swing.JLabel GebJahr;
    private javax.swing.JLabel GebTag;
    private javax.swing.JLabel Geburtsdatum;
    private javax.swing.JLabel Geschlecht;
    private javax.swing.JLabel Geschlecht1;
    private javax.swing.JLabel Hausnummer;
    private javax.swing.JLabel Hausnummer1;
    private javax.swing.JButton JbAuswahlenSb;
    private javax.swing.JLabel Klasse;
    private javax.swing.JLabel Klasse1;
    private javax.swing.JLabel Kontingent;
    private javax.swing.JLabel Kontingent1;
    private javax.swing.JLabel Matrikelnummer2Ss;
    private javax.swing.JLabel MatrikelnummerSb;
    private javax.swing.JLabel MatrikelnummerSl;
    private javax.swing.JLabel MatrikelnummerSs;
    private javax.swing.JLabel Nachname;
    private javax.swing.JLabel Nachname1;
    private javax.swing.JLabel Nachname2Ss;
    private javax.swing.JLabel NachnameSb;
    private javax.swing.JLabel NachnameSl;
    private javax.swing.JLabel NachnameSs;
    private javax.swing.JLabel Ort;
    private javax.swing.JLabel Ort1;
    private javax.swing.JLabel PLZ;
    private javax.swing.JLabel PLZ1;
    private javax.swing.JLabel Praferenzreihenfolge;
    private javax.swing.JLabel Praferenzreihenfolge1;
    private javax.swing.JLabel Schuleintrittsart;
    private javax.swing.JLabel Schuleintrittsart1;
    private javax.swing.JLabel Schuleintrittsnote;
    private javax.swing.JLabel Schuleintrittsnote1;
    private javax.swing.JLabel Schuleintrittsreihe;
    private javax.swing.JLabel Schuleintrittsreihe1;
    private javax.swing.JLabel Strasse;
    private javax.swing.JLabel Strasse1;
    private javax.swing.JPanel StudentKlasseZuteilen;
    private javax.swing.JPanel StudentNeu;
    private javax.swing.JPanel Studentbearbeiten;
    private javax.swing.JPanel Studentlöschen;
    private javax.swing.JPanel Studentsuchen;
    private javax.swing.JLabel TC;
    private javax.swing.JLabel TC1;
    private javax.swing.JLabel Tel;
    private javax.swing.JLabel Tel1;
    private javax.swing.JTextField TfBezirk;
    private javax.swing.JTextField TfBezirk1Sb;
    private javax.swing.JTextField TfElternvertreter;
    private javax.swing.JTextField TfElternvertreter1Sb;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfEmail1Sb;
    private javax.swing.JTextField TfFach;
    private javax.swing.JTextField TfFach1Sb;
    private javax.swing.JTextField TfFremdsprache;
    private javax.swing.JTextField TfFremdsprache1Sb;
    private javax.swing.JTextField TfGebTag1Sb;
    private javax.swing.JTextField TfGeschlecht;
    private javax.swing.JTextField TfGeschlecht1Sb;
    private javax.swing.JTextField TfHausnummer;
    private javax.swing.JTextField TfHausnummer1Sb;
    private javax.swing.JTextField TfKlasse;
    private javax.swing.JTextField TfKlasse1Sb;
    private javax.swing.JTextField TfKontingent;
    private javax.swing.JTextField TfKontingent1Sb;
    private javax.swing.JTextField TfMatrikelnummer2Ss;
    private javax.swing.JTextField TfMatrikelnummerSb;
    private javax.swing.JTextField TfMatrikelnummerSl;
    private javax.swing.JTextField TfMatrikelnummerSs;
    private javax.swing.JTextField TfNachname;
    private javax.swing.JTextField TfNachname1Sb;
    private javax.swing.JTextField TfNachname2Ss;
    private javax.swing.JTextField TfNachnameSb;
    private javax.swing.JTextField TfNachnameSl;
    private javax.swing.JTextField TfNachnameSs;
    private javax.swing.JTextField TfOrt;
    private javax.swing.JTextField TfOrt1Sb;
    private javax.swing.JTextField TfPLZ;
    private javax.swing.JTextField TfPLZ1Sb;
    private javax.swing.JTextField TfPraferenzreihenfolge;
    private javax.swing.JTextField TfPraferenzreihenfolge1Sb;
    private javax.swing.JTextField TfSchuleintrittsart;
    private javax.swing.JTextField TfSchuleintrittsart1Sb;
    private javax.swing.JTextField TfSchuleintrittsnote;
    private javax.swing.JTextField TfSchuleintrittsnote1Sb;
    private javax.swing.JTextField TfSchuleintrittsreihe;
    private javax.swing.JTextField TfSchuleintrittsreihe1Sb;
    private javax.swing.JTextField TfStrasse;
    private javax.swing.JTextField TfStrasse1Sb;
    private javax.swing.JTextField TfTC;
    private javax.swing.JTextField TfTC1Sb;
    private javax.swing.JTextField TfTel;
    private javax.swing.JTextField TfTel1Sb;
    private javax.swing.JTextField TfVorname;
    private javax.swing.JTextField TfVorname1Sb;
    private javax.swing.JTextField TfVorname2Ss;
    private javax.swing.JTextField TfVornameErziehungsberechtigter;
    private javax.swing.JTextField TfVornameErziehungsberechtigter1Sb;
    private javax.swing.JTextField TfVornameSb;
    private javax.swing.JTextField TfVornameSl;
    private javax.swing.JTextField TfVornameSs;
    private javax.swing.JLabel Vorname;
    private javax.swing.JLabel Vorname1;
    private javax.swing.JLabel Vorname2Ss;
    private javax.swing.JLabel VornameErziehungsberechtigter;
    private javax.swing.JLabel VornameErziehungsberechtigter1;
    private javax.swing.JLabel VornameSb;
    private javax.swing.JLabel VornameSl;
    private javax.swing.JLabel VornameSs;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
